#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp*/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
option space pxelinux;
#ignore client-updates;
allow booting;
allow bootp;
#allow unknown-clients;
#authoritative;
subnet 192.168.142.0 netmask 255.255.255.0 {
	range 192.168.142.101 192.168.142.120;
	option domain-name-servers 192.168.142.10;
	option routers 192.168.142.10;

next-server 192.168.142.10;
filename "pxelinux.0";
#filename "/pxelinux/pxelinux.0";
}
